version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  express:
    build: ./backend
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockeraws
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
